services:
  web:
    build: ./hotel_backend
    volumes:
      - ./hotel_backend:/usr/src/hotel_backend/
    ports:
      - 8000:8000
    env_file:
      - ./hotel_backend/.env.dev
    depends_on:
      - db
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=hoteldb

volumes:
  postgres_data:
