# Generated by Django 5.1.4 on 2024-12-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_bathrooms_property_favorited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='favorited',
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(),
        ),
    ]
